- name: First Task
  hosts: webservers

  tasks:
  -  copy: src=/home/centos/webhook/file.txt dest=/home/centos/
  -  shell: ls -lrt > temp.txt

- name: Second task
  hosts: dbservers

  roles:
  - common

- name: Debug example
  hosts: dbservers

  tasks:
  - debug: "{{ item }}"
  
    with_items:
    - abcd
      defgh
